# Create a program that lists all the elements in a list that are less than 5
list = [1,1,2,3,5,8,13,21,34,55,89] # creates the list of numbers and assigns it to the variable "list"
for element in list: # in other words, for all the elements in this variable...
    if element <5: # if that element is less than 5...
        print(element) # print the variable.
